// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: rpc_add_user_to_family.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUserToFamilyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CanRead   bool   `protobuf:"varint,2,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	CanEdit   bool   `protobuf:"varint,3,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`
	CanCreate bool   `protobuf:"varint,4,opt,name=can_create,json=canCreate,proto3" json:"can_create,omitempty"`
	CanModify bool   `protobuf:"varint,5,opt,name=can_modify,json=canModify,proto3" json:"can_modify,omitempty"`
}

func (x *AddUserToFamilyRequest) Reset() {
	*x = AddUserToFamilyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_add_user_to_family_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserToFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToFamilyRequest) ProtoMessage() {}

func (x *AddUserToFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_user_to_family_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToFamilyRequest.ProtoReflect.Descriptor instead.
func (*AddUserToFamilyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_add_user_to_family_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserToFamilyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserToFamilyRequest) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

func (x *AddUserToFamilyRequest) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *AddUserToFamilyRequest) GetCanCreate() bool {
	if x != nil {
		return x.CanCreate
	}
	return false
}

func (x *AddUserToFamilyRequest) GetCanModify() bool {
	if x != nil {
		return x.CanModify
	}
	return false
}

type AddUserToFamilyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User        *User        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Permissions *Permissions `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *AddUserToFamilyResponse) Reset() {
	*x = AddUserToFamilyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_add_user_to_family_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserToFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToFamilyResponse) ProtoMessage() {}

func (x *AddUserToFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_user_to_family_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToFamilyResponse.ProtoReflect.Descriptor instead.
func (*AddUserToFamilyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_add_user_to_family_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserToFamilyResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AddUserToFamilyResponse) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_rpc_add_user_to_family_proto protoreflect.FileDescriptor

var file_rpc_add_user_to_family_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74,
	0x6f, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa5, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x46,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x61, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x6e, 0x5f, 0x65, 0x64, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x61, 0x6e, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x63, 0x61, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61,
	0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x63, 0x61, 0x6e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x22, 0x6a, 0x0a, 0x17, 0x41, 0x64, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x31, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x65, 0x6d, 0x78, 0x69, 0x6e, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2d,
	0x6c, 0x69, 0x66, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_add_user_to_family_proto_rawDescOnce sync.Once
	file_rpc_add_user_to_family_proto_rawDescData = file_rpc_add_user_to_family_proto_rawDesc
)

func file_rpc_add_user_to_family_proto_rawDescGZIP() []byte {
	file_rpc_add_user_to_family_proto_rawDescOnce.Do(func() {
		file_rpc_add_user_to_family_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_add_user_to_family_proto_rawDescData)
	})
	return file_rpc_add_user_to_family_proto_rawDescData
}

var file_rpc_add_user_to_family_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_add_user_to_family_proto_goTypes = []any{
	(*AddUserToFamilyRequest)(nil),  // 0: pb.AddUserToFamilyRequest
	(*AddUserToFamilyResponse)(nil), // 1: pb.AddUserToFamilyResponse
	(*User)(nil),                    // 2: pb.User
	(*Permissions)(nil),             // 3: pb.Permissions
}
var file_rpc_add_user_to_family_proto_depIdxs = []int32{
	2, // 0: pb.AddUserToFamilyResponse.user:type_name -> pb.User
	3, // 1: pb.AddUserToFamilyResponse.permissions:type_name -> pb.Permissions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_add_user_to_family_proto_init() }
func file_rpc_add_user_to_family_proto_init() {
	if File_rpc_add_user_to_family_proto != nil {
		return
	}
	file_user_proto_init()
	file_permissions_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_add_user_to_family_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddUserToFamilyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_add_user_to_family_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddUserToFamilyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_add_user_to_family_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_add_user_to_family_proto_goTypes,
		DependencyIndexes: file_rpc_add_user_to_family_proto_depIdxs,
		MessageInfos:      file_rpc_add_user_to_family_proto_msgTypes,
	}.Build()
	File_rpc_add_user_to_family_proto = out.File
	file_rpc_add_user_to_family_proto_rawDesc = nil
	file_rpc_add_user_to_family_proto_goTypes = nil
	file_rpc_add_user_to_family_proto_depIdxs = nil
}
