// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: rpc_get_tasks.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchBy int32

const (
	SearchBy_FAMILY_ID   SearchBy = 0
	SearchBy_ASSIGNED_TO SearchBy = 1
)

// Enum value maps for SearchBy.
var (
	SearchBy_name = map[int32]string{
		0: "FAMILY_ID",
		1: "ASSIGNED_TO",
	}
	SearchBy_value = map[string]int32{
		"FAMILY_ID":   0,
		"ASSIGNED_TO": 1,
	}
)

func (x SearchBy) Enum() *SearchBy {
	p := new(SearchBy)
	*p = x
	return p
}

func (x SearchBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchBy) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_get_tasks_proto_enumTypes[0].Descriptor()
}

func (SearchBy) Type() protoreflect.EnumType {
	return &file_rpc_get_tasks_proto_enumTypes[0]
}

func (x SearchBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchBy.Descriptor instead.
func (SearchBy) EnumDescriptor() ([]byte, []int) {
	return file_rpc_get_tasks_proto_rawDescGZIP(), []int{0}
}

type GetTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchBy SearchBy               `protobuf:"varint,1,opt,name=search_by,json=searchBy,proto3,enum=pb.SearchBy" json:"search_by,omitempty"`
	DateFrom *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_tasks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_tasks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *GetTasksRequest) GetSearchBy() SearchBy {
	if x != nil {
		return x.SearchBy
	}
	return SearchBy_FAMILY_ID
}

func (x *GetTasksRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetTasksRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

type GetTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_tasks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_tasks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *GetTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_rpc_get_tasks_proto protoreflect.FileDescriptor

var file_rpc_get_tasks_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x09, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x52, 0x08, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x42, 0x79, 0x12, 0x37, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x33,
	0x0a, 0x07, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x22, 0x32, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2a, 0x2a, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x42, 0x79, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59, 0x5f, 0x49, 0x44,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x53, 0x53, 0x49, 0x47, 0x4e, 0x45, 0x44, 0x5f, 0x54,
	0x4f, 0x10, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x52, 0x65, 0x6d, 0x78, 0x69, 0x6e, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2d, 0x6c, 0x69,
	0x66, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_get_tasks_proto_rawDescOnce sync.Once
	file_rpc_get_tasks_proto_rawDescData = file_rpc_get_tasks_proto_rawDesc
)

func file_rpc_get_tasks_proto_rawDescGZIP() []byte {
	file_rpc_get_tasks_proto_rawDescOnce.Do(func() {
		file_rpc_get_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_get_tasks_proto_rawDescData)
	})
	return file_rpc_get_tasks_proto_rawDescData
}

var file_rpc_get_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_get_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_tasks_proto_goTypes = []any{
	(SearchBy)(0),                 // 0: pb.SearchBy
	(*GetTasksRequest)(nil),       // 1: pb.GetTasksRequest
	(*GetTasksResponse)(nil),      // 2: pb.GetTasksResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Task)(nil),                  // 4: pb.Task
}
var file_rpc_get_tasks_proto_depIdxs = []int32{
	0, // 0: pb.GetTasksRequest.search_by:type_name -> pb.SearchBy
	3, // 1: pb.GetTasksRequest.date_from:type_name -> google.protobuf.Timestamp
	3, // 2: pb.GetTasksRequest.date_to:type_name -> google.protobuf.Timestamp
	4, // 3: pb.GetTasksResponse.tasks:type_name -> pb.Task
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_get_tasks_proto_init() }
func file_rpc_get_tasks_proto_init() {
	if File_rpc_get_tasks_proto != nil {
		return
	}
	file_task_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_get_tasks_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_tasks_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_get_tasks_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_tasks_proto_goTypes,
		DependencyIndexes: file_rpc_get_tasks_proto_depIdxs,
		EnumInfos:         file_rpc_get_tasks_proto_enumTypes,
		MessageInfos:      file_rpc_get_tasks_proto_msgTypes,
	}.Build()
	File_rpc_get_tasks_proto = out.File
	file_rpc_get_tasks_proto_rawDesc = nil
	file_rpc_get_tasks_proto_goTypes = nil
	file_rpc_get_tasks_proto_depIdxs = nil
}
