name: home-life
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=zaq12WSX
    ports:
      - "5432:5432"
    
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
