DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "families" CASCADE;
DROP TABLE IF EXISTS "tasks" CASCADE;
DROP TABLE IF EXISTS "recipes";
DROP TABLE IF EXISTS "verify_emails";
DROP TABLE IF EXISTS "permissions" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;