// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Family struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Owner uuid.UUID `json:"owner"`
}

type Permission struct {
	ID        uuid.UUID `json:"id"`
	CanRead   bool      `json:"can_read"`
	CanEdit   bool      `json:"can_edit"`
	CanCreate bool      `json:"can_create"`
}

type Recipe struct {
	ID          uuid.UUID `json:"id"`
	CreatedBy   uuid.UUID `json:"created_by"`
	Public      bool      `json:"public"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	ImageLink   string    `json:"image_link"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Task struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Family      uuid.UUID     `json:"family"`
	CreatedBy   uuid.UUID     `json:"created_by"`
	AssignedTo  uuid.NullUUID `json:"assigned_to"`
	Date        time.Time     `json:"date"`
	CreatedAt   time.Time     `json:"created_at"`
}

type User struct {
	ID                uuid.UUID     `json:"id"`
	Name              string        `json:"name"`
	Email             string        `json:"email"`
	Password          string        `json:"password"`
	IsVerified        bool          `json:"is_verified"`
	Family            uuid.NullUUID `json:"family"`
	PasswordChangedAt time.Time     `json:"password_changed_at"`
	CreatedAt         time.Time     `json:"created_at"`
}

type VerifyEmail struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
