// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: permission.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPermissions = `-- name: CreatePermissions :one
INSERT INTO "permissions" (
    id,
    family_id,
    can_read,
    can_edit,
    can_create,
    can_modify
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, family_id, can_read, can_edit, can_create, can_modify
`

type CreatePermissionsParams struct {
	ID        uuid.UUID `json:"id"`
	FamilyID  uuid.UUID `json:"family_id"`
	CanRead   bool      `json:"can_read"`
	CanEdit   bool      `json:"can_edit"`
	CanCreate bool      `json:"can_create"`
	CanModify bool      `json:"can_modify"`
}

func (q *Queries) CreatePermissions(ctx context.Context, arg CreatePermissionsParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createPermissions,
		arg.ID,
		arg.FamilyID,
		arg.CanRead,
		arg.CanEdit,
		arg.CanCreate,
		arg.CanModify,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.CanRead,
		&i.CanEdit,
		&i.CanCreate,
		&i.CanModify,
	)
	return i, err
}

const getPermissions = `-- name: GetPermissions :one
SELECT id, family_id, can_read, can_edit, can_create, can_modify FROM "permissions"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPermissions(ctx context.Context, id uuid.UUID) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissions, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.CanRead,
		&i.CanEdit,
		&i.CanCreate,
		&i.CanModify,
	)
	return i, err
}
