// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToFamily(ctx context.Context, arg AddUserToFamilyParams) (User, error)
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error)
	CreatePermissions(ctx context.Context, arg CreatePermissionsParams) (Permission, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	GetMembers(ctx context.Context, familyID uuid.NullUUID) ([]GetMembersRow, error)
	GetPermissions(ctx context.Context, id uuid.UUID) (Permission, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
